name: build-windows

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: choco install python visualstudio2017-workload-vctools -y
      - run: npm config set msvs_version 2017 --global
      - run: npm install
      - run: npm run prebuild
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: upload binaries
        uses: actions/github-script@v6
        with:
          script: |
            const zip = require('cross-zip')
            
            const script = require('./scripts/upload-binaries.js');

            await script({
              github,
              context,
              core,
              zip
            }); 
