name: build-linux

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7.x'
      - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - run: sudo apt-get update
      - run: sudo apt-get install libxtst-dev libpng++-dev gcc-7 g++-7 -y
      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - run: npm install --loglevel verbose
      - run: npm run prebuild
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: upload binaries
        uses: actions/github-script@v6
        with:
          script: |
            const zip = require('cross-zip')
            
            const script = require('./scripts/upload-binaries.js');

            await script({
              github,
              context,
              core,
              zip
            }); 
